Fix `args.filter is not a function`
(node:75617) UnhandledPromiseRejectionWarning: TypeError: args.filter is not a function
    at handleCommandLineArguments (/home/ahann/Documents/GitHub/desktop/dist/github-desktop-dev-linux-x64/resources/app/main.js:48414:44)
    at /home/ahann/Documents/GitHub/desktop/dist/github-desktop-dev-linux-x64/resources/app/main.js:48350:5
    at /home/ahann/Documents/GitHub/desktop/dist/github-desktop-dev-linux-x64/resources/app/main.js:48802:3
    at Object.<anonymous> (/home/ahann/Documents/GitHub/desktop/dist/github-desktop-dev-linux-x64/resources/app/main.js:48805:12)
    at Module._compile (node:internal/modules/cjs/loader:1562:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1715:10)
    at Module.load (node:internal/modules/cjs/loader:1296:32)
    at Module._load (node:internal/modules/cjs/loader:1115:12)
    at c._load (node:electron/js2c/node_init:2:17950)
    at node:electron/js2c/browser_init:2:134953
(Use `github-desktop-dev --trace-warnings ...` to show where the warning was created)
(node:75617) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)